// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/nested.proto

package validator_examples

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/utilitywarehouse/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InnerMessage struct {
	// some_integer can only be in range (1, 100).
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMessage) Reset()         { *m = InnerMessage{} }
func (m *InnerMessage) String() string { return proto.CompactTextString(m) }
func (*InnerMessage) ProtoMessage()    {}
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_nested_94c712f41b35d3b7, []int{0}
}
func (m *InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessage.Unmarshal(m, b)
}
func (m *InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessage.Marshal(b, m, deterministic)
}
func (dst *InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessage.Merge(dst, src)
}
func (m *InnerMessage) XXX_Size() int {
	return xxx_messageInfo_InnerMessage.Size(m)
}
func (m *InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessage proto.InternalMessageInfo

func (m *InnerMessage) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type OuterMessage struct {
	// important_string must be a lowercase alpha-numeric of 5 to 30 characters (RE2 syntax).
	ImportantString string `protobuf:"bytes,1,opt,name=important_string,json=importantString,proto3" json:"important_string,omitempty"`
	// proto3 doesn't have `required`, the `msg_exist` enforces presence of InnerMessage.
	Inner                *InnerMessage `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OuterMessage) Reset()         { *m = OuterMessage{} }
func (m *OuterMessage) String() string { return proto.CompactTextString(m) }
func (*OuterMessage) ProtoMessage()    {}
func (*OuterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_nested_94c712f41b35d3b7, []int{1}
}
func (m *OuterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterMessage.Unmarshal(m, b)
}
func (m *OuterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterMessage.Marshal(b, m, deterministic)
}
func (dst *OuterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterMessage.Merge(dst, src)
}
func (m *OuterMessage) XXX_Size() int {
	return xxx_messageInfo_OuterMessage.Size(m)
}
func (m *OuterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OuterMessage proto.InternalMessageInfo

func (m *OuterMessage) GetImportantString() string {
	if m != nil {
		return m.ImportantString
	}
	return ""
}

func (m *OuterMessage) GetInner() *InnerMessage {
	if m != nil {
		return m.Inner
	}
	return nil
}

func init() {
	proto.RegisterType((*InnerMessage)(nil), "validator.examples.InnerMessage")
	proto.RegisterType((*OuterMessage)(nil), "validator.examples.OuterMessage")
}

func init() { proto.RegisterFile("examples/nested.proto", fileDescriptor_nested_94c712f41b35d3b7) }

var fileDescriptor_nested_94c712f41b35d3b7 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xcd, 0x70, 0x43, 0xb3, 0xa2, 0x23, 0x20, 0x14, 0x2f, 0x2d, 0xc3, 0xc3, 0x40, 0x9b,
	0xc2, 0xc4, 0x93, 0xa8, 0xd0, 0xdb, 0x0e, 0x22, 0xd4, 0xa3, 0xe8, 0xc8, 0xec, 0x4b, 0x16, 0x68,
	0x93, 0x92, 0xbc, 0xf5, 0x2f, 0x7e, 0x04, 0x3f, 0x63, 0xa1, 0x9f, 0x44, 0x96, 0xe1, 0x26, 0x78,
	0x7e, 0x7e, 0xbf, 0x87, 0xe7, 0xa1, 0x47, 0xf0, 0x26, 0xaa, 0xba, 0x04, 0x97, 0x6a, 0x70, 0x08,
	0x05, 0xaf, 0xad, 0x41, 0xc3, 0xd8, 0x8b, 0x28, 0x55, 0x21, 0xd0, 0x58, 0xfe, 0x0b, 0x1c, 0xdf,
	0x48, 0x85, 0xcb, 0x66, 0xc1, 0x9f, 0x4d, 0x95, 0x36, 0xa8, 0x4a, 0x85, 0xef, 0xaf, 0xc2, 0xc2,
	0xd2, 0x34, 0x0e, 0x52, 0x69, 0x12, 0x6f, 0x26, 0x1b, 0xd1, 0xa5, 0xdb, 0x0e, 0x1f, 0x8d, 0x2f,
	0x69, 0x30, 0xd3, 0x1a, 0xec, 0x2d, 0x38, 0x27, 0x24, 0xb0, 0x53, 0x1a, 0x38, 0x53, 0xc1, 0x5c,
	0x69, 0x04, 0x09, 0x36, 0x24, 0x31, 0x99, 0xf4, 0xb3, 0xbd, 0xae, 0x8d, 0x76, 0x47, 0x3b, 0x61,
	0x91, 0x0f, 0x57, 0xe9, 0x6c, 0x1d, 0x8e, 0xbf, 0x09, 0x0d, 0xee, 0x1a, 0xdc, 0xda, 0x57, 0x74,
	0xa4, 0xaa, 0xda, 0x58, 0x14, 0x1a, 0xe7, 0x0e, 0xad, 0xd2, 0xd2, 0x37, 0xec, 0x67, 0xac, 0x6b,
	0xa3, 0x03, 0x1a, 0x3c, 0x3d, 0x88, 0xe4, 0xe3, 0xf1, 0x73, 0x7a, 0x76, 0xf1, 0x75, 0x92, 0x1f,
	0x6e, 0xd8, 0x7b, 0x8f, 0xb2, 0x6b, 0xda, 0x57, 0xab, 0x31, 0x61, 0x2f, 0x26, 0x93, 0xe1, 0x34,
	0xe6, 0xff, 0x1f, 0xf3, 0xbf, 0x6b, 0xb3, 0x41, 0xd7, 0x46, 0xbd, 0x98, 0xe4, 0x6b, 0x6d, 0x31,
	0xf0, 0x9f, 0xce, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x63, 0xda, 0x14, 0xff, 0x41, 0x01, 0x00,
	0x00,
}
